name: DMS Webview CI

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfixes'
      - 'release/**'
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'

# 동일한 브랜치/PR에 대한 동시 실행을 방지하고, 최신 커밋에 대한 워크플로우만 실행합니다.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # yarn 캐시를 활성화하여 의존성 설치 속도를 향상시킵니다.
          cache: 'yarn'

      # .env 파일을 생성하여 빌드 시 환경변수를 주입합니다.
      # axios.ts에서 process.env.REACT_APP_BASE_URL을 사용하므로, 변수 이름을 이에 맞춥니다.
      - name: Create .env file
        env:
          # GitHub Repository Secret에 저장된 DMS_WEBVIEW_DOMAIN 값을 가져옵니다.
          REACT_APP_BASE_URL: ${{ secrets.DMS_WEBVIEW_DOMAIN }}
        run: |
          echo "REACT_APP_BASE_URL=${REACT_APP_BASE_URL}" >> .env

      - name: Install dependencies
        # --frozen-lockfile 옵션은 yarn.lock 파일을 기준으로 정확한 버전의 패키지를 설치하도록 강제합니다.
        run: yarn install --frozen-lockfile

      - name: Build project
        # DISABLE_ESLINT_PLUGIN=true는 빌드 시 ESLint 오류를 무시하는 설정입니다.
        # CI 환경에서 빌드 성공 여부만 확인할 때 종종 사용됩니다.
        run: DISABLE_ESLINT_PLUGIN=true yarn build
